version: '3'
services:
  web:
    container_name: web
    image: zcbm7008/second-eyes-web
    expose:
      - 8080
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    image: zcbm7008/second-eyes-nginx
    ports:
      - 80:80
    depends_on:
      - web